#!/bin/bash

# This 'setup' script is where you can add steps that should be run each
# time the container for the workshop is started. Note that if you are
# using persistent storage with a workshop and make changes to files from
# this script, or are deploying applications, your scripts must cope with
# the steps having already been run. This is because this script will be
# run a second time if the container were restarted for some reason.

# Set up git caching of password
#git config --global credential.helper 'cache --timeout=3600'
git config --global credential.helper store
git config --global push.default matching  # squelch the push.default message

umask 077
