#!/bin/bash

# This 'setup' script is where you can add steps that should be run each
# time the container for the workshop is started. Note that if you are
# using persistent storage with a workshop and make changes to files from
# this script, or are deploying applications, your scripts must cope with
# the steps having already been run. This is because this script will be
# run a second time if the container were restarted for some reason.

cat > setup.sh <<'END'
# Run this to fork the repo

cd ~/
rm -rf lab-workshop-content/
git clone https://github.com/openshift-labs/lab-workshop-content.git
cd lab-workshop-content/
while ! hub fork
do
        echo
        echo Please try again ...
        sleep 1
done
cd ..
rm -rf lab-workshop-content
if [ -f ~/.config/hub ]
then
        U=`cat ~/.config/hub | grep user: | awk '{print $NF}'`
        git clone https://github.com/$U/lab-workshop-content.git
        #cd lab-workshop-content
else
        echo
        echo Please run the script again
fi
END

chmod 700 setup.sh 
