#!/bin/bash 

echo Stoping the application 
oc scale dc vote-app --replicas=0

echo Deleting the database ...
mysql -h db.`oc project -q`.svc -u user -ppassword -D vote -e 'drop table `option`;'
mysql -h db.`oc project -q`.svc -u user -ppassword -D vote -e 'delete from `poll`;'

echo Starting the application 
oc scale dc vote-app --replicas=1 

