#!/bin/bash -e
# Script to extract all values (.data.*) in a secret into shell env vars

BASE=`basename $0`
[ $# -ne 1 ] && echo "Usage: $BASE secret" && exit 1

VARS=$(oc get secret $1 -o json | jq ".data" | tail -n +2 | head -n -1 | cut -d\" -f2)

for i in $VARS
do
        echo -n "$i='"
        oc get secret $1 -o template --template {{.data.$i}} | base64 -d
        echo "'"
done

