#!/bin/bash

[ $# -ne 1 ] && echo "Usage example: test-vote-app http://example.com:8080" && exit 1

for i in {1..20}
do
   echo Casting vote nr. $i
   RESP=$(curl -o /tmp/.tempfile -w "%{http_code}\n" -s -X POST $1/vote.html -d "vote=`expr $(($RANDOM % 10)) + 1`")
   [ "$RESP" != "200" ] && echo HTTP return code: $RESP && cat /tmp/.tempfile && echo Aborting test script ... && exit 1
done

