#!/bin/bash

[ $# -ne 1 ] && echo "Usage: test-vote-app: vote-app-url" && exit 1

for i in {1..20}
do
   echo Casting vote nr. $i
   RESP=$(curl -o /tmp/.tempfile -w "%{http_code}\n" -s -X POST $1 -d "vote=`expr $(($RANDOM % 10)) + 1`")
   [ "$RESP" != "200" ] && echo HTTP return code: $RESP && cat /tmp/.tempfile && echo Aborting test script ... && exit 1
done

